### ISSUE TITLE
oosplash file missing

### ISSUE THREAD

**Issue by jivenhui** [shelfio/libreoffice-lambda-layer#10]
I use this layer to convert a pptx file to svg with the following repo: aws-lambda-libreoffice. But when i run the convert to command it says the following: '/tmp/instdir/program/oosplash: No such file or directory'. When i look into the program folder it is indeed missing the oosplash file. Is it possible for a pptx file to be converted to a svg file?

**Comment by esperienzia** [comment]
I just got the same errore while converting a docx to pdf using the module @shelf/aws-lambda-libreoffice and this layer for the eu-west-1 region.

Here the error returned from the aws lambda:

`{"errorMessage":"Command failed: /tmp/instdir/program/soffice --headless --invisible --nodefault --view --nolockcheck --nologo --norestore --convert-to pdf --outdir /tmp /tmp/scheda.docx\n/tmp/instdir/program/soffice: line 174: /tmp/instdir/program/oosplash: No such file or directory\n","errorType":"Error","stackTrace":["/tmp/instdir/program/soffice: line 174: /tmp/instdir/program/oosplash: No such file or directory","","checkExecSyncError (child_process.js:601:13)","execSync (child_process.js:641:13)","exports.handler (/var/task/index.js:19:3)","<anonymous>","process._tickDomainCallback (internal/process/next_tick.js:228:7)"]}
`

**Comment by esperienzia** [comment]
Hi @vladgolubev i have found the problem and even the solution to problem above.

The reason why it couldn't find the oosplash is because the lambda function need enough time and space to unpack the lo.tar.br (in this case only a part of the files were unpacked).

 I just set the memory memory to 512MB and timeout to 5 min and everything worked as expected.

**Comment by vladgolubev** [comment]
Glad to hear that, @esperienzia!

I suggest setting 1536 or even 3008 MB, it will make things significantly faster

**Comment by vladgolubev** [comment]
@jivenhui I see you upvoted @esperienzia's comment, did it solve your issue so I can close this one?

**Comment by ChillkroeteTTS** [comment]
@vladgolubev I experienced the same issue @esperienzia and setting memory and timeout to the values you recommended did the trick for me.

Since it took me 2h to figure out, I wanna mention that the Issue appeared for me when I moved my code from JS to Webpack bundled Typescript. Since Webpack throwed errors at me when processing the 'iltorb.node' file of the aws-lambda-brotli-unpacker repo, I had to use this workaround to get it running. https://github.com/webpack-contrib/node-loader/issues/12#issuecomment-334116820
